### ISSUE TITLE
Http 500 Internal server error 

### ISSUE THREAD

**Issue by xingstarx** [Harlber/Moose#35]
之声
Http 500 Internal server error ?
acfun 服务器不再提供接口呢？

**Comment by xingstarx** [comment]
刚fork这个项目，准备学习下，不会就gg 思密达了吧。。

**Comment by Harlber** [comment]
是的，列表页的api  出问题了，目前
http://api.acfun.tv/apiserver/content/channel?orderBy=0&channelId=75&pageSize=20&pageNo=1
和http://api.acfun.tv/apiserver/content/channel?orderBy=0&channelId=74&pageSize=20&pageNo=1
是存活的，我这几天会去研究下

**Comment by xingstarx** [comment]
恩，good
这样我也好学习啊，先献出我的膝盖。。

**Comment by Harlber** [comment]
接口那边改动很大，目前【动漫文化】和【漫画小说】可以获得一页数据 [点击查看](https://github.com/Harlber/Moose/commit/a6cdef70996aab69d8223846e8453aa76eeabc73)
感觉这次是A站有意弃用之前的api，而且到目前为止A站这边也没有公开申请的api，关于这个问题目前已经给官方写了封信了，等待回复中~

**Comment by Harlber** [comment]
https://www.zhihu.com/question/49243220#

**Comment by xingstarx** [comment]
http 500又出现了，估计接口得好好调整下了

**Comment by Harlber** [comment]
嗯，A站的后台今年开始就不稳定，上次给官方写了封信询问开放api的事，目前仍未收到消息

**Comment by shihangwei** [comment]
ggwp

**Comment by Harlber** [comment]
准备抓官方应用的数据包

**Comment by xingstarx** [comment]
good

**Comment by Harlber** [comment]
see also #41
