### ISSUE TITLE
ArticleViewActivity里面的菜单选项，收藏功能

### ISSUE THREAD

**Issue by xingstarx** [Harlber/Moose#50]
点击收藏，或者是取消收藏，不是会弹snackbar吗，对于有FloatingActionButton的，会进行级联往上浮动，这个是没有问题的。

对于人为点击了snack的onClick事件的操作的，FloatingActionButton没有办法回到原来的位置。

解决办法应该是将

```
Snackbar snackBar = Snackbar.make(mWeb, msg, Snackbar.LENGTH_SHORT);
```

mWeb改成  CoordinatorLayout对应的控件名称

**Comment by Harlber** [comment]
<img src="https://cloud.githubusercontent.com/assets/7955320/19296028/40f852d6-906b-11e6-803a-d06ba8a138a9.png" width = "300" height = "572" alt="issue_50" align=center />

**Comment by xingstarx** [comment]
恩，下次的issue，我还是得配张图，这样直白一些

**Comment by xingstarx** [comment]
dispatchDismiss(Callback.DISMISS_EVENT_MANUAL);//dismiss事件
dispatchDismiss(Callback.DISMISS_EVENT_ACTION);//处理setAction的click事件
snack源码里面是这样的

估计是不同的DISMISS事件类型决定这不同的行为，跟了下代码，看的不是很明显，这一块值得开个issue分析下Snackbar源码的dismiss过程。最终的Snackbar里面的hideView(int event)往下执行是怎么产生不同的行为，这一块我没看出来

```
final void hideView(int event) {
        if (mView.getVisibility() != View.VISIBLE || isBeingDragged()) {
            onViewHidden(event);
        } else {
            animateViewOut(event);
        }
    }
```

源码中的消失的方法是hideview(),之前的代码中，snackbar.dismiss()难道造成了snackbar的view的状态不是VISIBLE了吗。

反正我去掉了snackbar.dismiss()，这段代码后，就是正常的，有动画效果的，估计执行的是animateViewOut(event)方法，而原来的执行的是onViewHidden(event)。。

不太明白这个判断条件是什么时候变化的。

**Comment by xingstarx** [comment]
Done
