### ISSUE TITLE
Tint navigation bar

### ISSUE THREAD

**Issue by Harlber** [Harlber/Moose#51]
Looks like
<img src="https://cloud.githubusercontent.com/assets/7955320/19303100/e2279486-9099-11e6-9617-05868105f61f.png" width = "300" height = "572" alt="issue_51" align=center />

**Comment by Harlber** [comment]
see commit https://github.com/Harlber/Moose/commit/131023cb0ac14e214b1d586d809e41b2c645d419

**Comment by Harlber** [comment]
api21 
<img src="https://cloud.githubusercontent.com/assets/7955320/19336298/abf1dab8-913c-11e6-9d04-b122babe0353.png" width = "300" height = "572" alt="issue_51_1" align=center />

api24
<img src="https://cloud.githubusercontent.com/assets/7955320/19336315/cbb306a6-913c-11e6-8a29-ebf98e302867.png" width = "300" height = "572" alt="issue_5_2" align=center />

**Comment by xingstarx** [comment]
这两个效果不是一样的吗
