### ISSUE TITLE
acfun评论相关的接口信息

### ISSUE THREAD

**Issue by xingstarx** [Harlber/Moose#59]
查看一篇文章下的评论
`http://mobile.app.acfun.cn/comment/content/list?version=4&contentId=3181117&pageSize=50&pageNo=2`

**Comment by xingstarx** [comment]
`http://mobile.app.acfun.cn/comment.aspx`
![moose_2016_10_16_001](https://cloud.githubusercontent.com/assets/8245264/19416594/edea5bde-93c6-11e6-8509-a26f3748d55a.png)

**Comment by xingstarx** [comment]
![moose_2016_10_16_002](https://cloud.githubusercontent.com/assets/8245264/19416642/5177f1c4-93c8-11e6-908f-7ace4eae1fc6.png)

**Comment by xingstarx** [comment]
可以看看这个分支 
https://github.com/Harlber/Moose/tree/feature-new-comment-api

**Comment by xingstarx** [comment]
还没有改完写评论的接口，添加新的评论估计得严格模仿官方的app的效果额。原来的感觉只能在最后添加额

**Comment by xingstarx** [comment]
添加评论的新接口，出现问题了
 `{"success":false,"msg":"user is not found","status":401}`

官方的请求接口中，是带有这个参数的

```
captcha 
text    还是可以的啦:smile:
source  mobile
quoteId 68021289
access_token    WkdVk9zcyU6BAfuqIpw4KaCJZMGGwtZb
contentId   3218357
userId  6479165
```

`access_token`

**Comment by Harlber** [comment]
看这样子是登陆后，获取的token

**Comment by xingstarx** [comment]
恩，得看看怎么样才能获取到这个token

**Comment by xingstarx** [comment]
接上次，有这个`token`，发现也不能添加评论，还需要研究下，为什么不行

**Comment by xingstarx** [comment]
测试成功了，之前的代码采用的是application/json形式的请求

```
@POST(Config.API_COMMENT)
Observable<CommentSend> sendComment(@Body CommentBody commentBody);
```

官方的是application/x-www-form-urlencoded，所以做了修改，换成了原来的形式

```
@FormUrlEncoded
@POST(Config.API_COMMENT)
Observable<CommentSend> sendComment(@FieldMap Map<String, Object> map);
```

当然了，还需要调试下，看看具体需要哪些字段。。哪些是多余的。

**Comment by xingstarx** [comment]
经过测试，不需要带上`header`头信息了，只需要按照参数传递`map`就可以了。。当然了`access_token`是需要的

**Comment by xingstarx** [comment]
还存在几个问题：
1. 添加评论后，自动刷出来的数据重复了  _(完成)_
2. 需要想办法解决下软键盘的问题，目前的dialogFragment都成了全屏了。需要参考官方的效果调整下 _(未完成，暂时能用)_
3. 评论的activity，不需要用viewPager了，感觉可以去掉  _(完成)_
4. 普通的评论可以添加个FAB按钮,目前的都是引用评论的功能 _(完成)_

**Comment by Harlber** [comment]
嗯，评论的功能包含快速评论和引用评论，另外，现在网站上又了2种新表情，一方面在展示评论的时候需要支持，另一方面，发布评论的时候也需要支持（发布评论的格式转换我来做）

**Comment by xingstarx** [comment]
恩，可以，我先解决上面我提到的几个问题。。你说的问题，你先处理，有时间我也看看
